version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1691342274
layout:
  header: {  }
  navigation: {  }
  /hero/:
    -
      - herostaticcontent-4104
  heading: {  }
  /row-1/:
    -
      - contentblocks-5399
  row-2: {  }
  row-3: {  }
  row-4: {  }
  row-5: {  }
  row-6: {  }
  row-7: {  }
  row-8: {  }
  row-9: {  }
  row-10: {  }
  footer: {  }
  inject: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  hero:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'bg-center bg-cover'
      background: 'gantry-media://hero/children-writing.jpg'
  heading:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-1:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-2:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-3:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-4:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-5:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-6:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-7:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-8:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-9:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-10:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  inject:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  herostaticcontent-4104:
    title: 'Hero Static Content'
    attributes:
      class: nass-hero-content
      variations: ''
      backgroundImage: ''
      backgroundSize: bg-cover
      backgroundPosition: bg-center
      contentStyleClass: content-flush
      titlePrefix: ''
      title: 'Training and consultancy'
      titleTag: h1
      titleLarge: '0'
      subtitle: 'The voice of small schools'
      content: "NASS is a registered charity supporting and promoting the work of small schools across the UK.\n\n<a href=\"/home/join-nass\" class=\"btn-primary btn-arrow\">Join NASS</a>"
      contentSize: full
      url: ''
      urlText: ''
      urlClass: ''
      searchInput: '0'
      disable: '0'
  contentblocks-5399:
    title: 'Training and events content'
    attributes:
      items:
        -
          enabled: '1'
          titlePrefix: ''
          title: Training
          titleTag: h2
          content: "At NASS, we offer a wide range of training and events designed specifically for individuals working in and with small schools.\L\LFrom informal network meetings to full-scale Headteacher conferences, our programs are built to meet your needs and inspire leadership at every level.\L\L\n\nWe’re continually expanding our training options, working closely with trusted partners in the education sector to bring you even more valuable opportunities and resources.\L\L\n\nSmall schools face unique challenges, and we understand that effective leadership is key to their success. Partnering with NASS means having an advocate who has walked in your shoes and is here to support your school at every step. Together, we empower leaders, strengthen schools, and create thriving communities."
          bottomBorder: '0'
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: Training
        -
          enabled: '1'
          titlePrefix: ''
          title: 'Upcoming events'
          titleTag: h2
          content: "NASS runs a regular half-termly program of network meetings that provide a safe space for small school leaders to collaborate, share best practices, and concerns.\L\LNetwork meetings are open to all NASS members, or those working in member schools. A Zoom link is emailed to all our members in advance. Join us on one of the dates below to connect with like-minded colleagues from small schools.\n\nDates to follow"
          bottomBorder: '0'
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Upcoming events'
        -
          enabled: '1'
          titlePrefix: ''
          title: 'Networks and special interest groups'
          titleTag: h2
          content: "Our special interest groups help those involved with the work of small schools to find support and reflection with like-minded professionals. They ensure our members’ views are heard and help shape NASS’s future work.\n\n### Research special interest group\n\n#### Exploring the unique strengths of small schools\L\n\nNASS has a proud history of promoting and engaging with research that explores the unique aspects of small schools.\L\LOver the years, our trustees - past and present - have contributed to a wide range of projects and publications. We’ve also curated a substantial archive of articles and opinion pieces, reflecting decades of thought leadership and advocacy for small schools.\L\L\n\nIn our early years research, efforts focused on building evidence to support campaigns against threats to individual small schools and their viability as an educational model. Today, our research spans a broader range of topics, including:\L\L\n\n\n- Mixed-age teaching\n- Pupil attainment in disadvantaged groups\n- Voluntary and community engagement\n- Leadership in small school settings\n- Comparative studies on small schools around the world\L\L\n\nThe NASS Research SIG (Special Interest Group) is a small group of NASS members who are all passionate about research and small schools.\L\LThe group comprises academics, education advisers, headteachers, and postgraduate students. It meets six times a year on Zoom, with a spotlight on a particular research paper as a key talking point in each meeting.\L\L\n\nNo specific experience or qualifications are required, so if you would like to join the group, do get in touch!\L\LThe convenor is Gillian Seymour."
          bottomBorder: '0'
          iconListItems: {  }
          buttonItems: {  }
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Networks and special interest groups'
