version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1691342274
layout:
  header: {  }
  navigation: {  }
  hero: {  }
  /row-1/:
    -
      - markdown-9556
    -
      - 'contentblocks-9407 50'
      - 'image-2660 50'
    -
      - contentblocks-4106
  row-2: {  }
  row-3: {  }
  row-4: {  }
  row-5: {  }
  row-6: {  }
  row-7: {  }
  row-8: {  }
  row-9: {  }
  row-10: {  }
  footer: {  }
  inject: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  hero:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-1:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-2:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-3:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-4:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-5:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-6:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-7:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-8:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-9:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-10:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  inject:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  markdown-9556:
    title: Heading
    attributes:
      html: '## Chassis 001 - Chimaera (completed June 2021)'
  contentblocks-9407:
    title: 'Intro paragraph'
    attributes:
      items:
        -
          enabled: '1'
          titlePrefix: ''
          title: ''
          titleTag: div
          content: 'Originally started as a lockdown project in late 2020, this model TVR Chimaera (VIN No. ''01'') was built as a present for my 7yr old daughter and took over 500 hours to complete.'
          bottomBorder: '0'
          galleryId: '9'
          iconListItems: {  }
          buttonItems: {  }
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Intro paragraph and gallery 1'
  image-2660:
    attributes:
      image: 'gantry-media://pages/chimaera-replica/sophie-with-cimaera-replica.jpg'
      text: 'Sophie with the TVR Chimaera replica'
  contentblocks-4106:
    title: 'Content Blocks'
    attributes:
      items:
        -
          enabled: '1'
          titlePrefix: ''
          title: ''
          titleTag: div
          content: "The shape was first carved out of rigid foam insulation sheets and then refined using body filler.\n\n"
          bottomBorder: '0'
          galleryId: '10'
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Shape and gallery 2'
        -
          enabled: '1'
          titlePrefix: ''
          title: ''
          titleTag: div
          content: 'Moulds were then taken and the bodyshell recreated in fibreglass.'
          bottomBorder: '0'
          galleryId: ''
          iconListItems: {  }
          buttonItems: {  }
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Moulds and gallery 3'
        -
          enabled: '1'
          titlePrefix: ''
          title: ''
          titleTag: div
          content: 'The chassis is partly based on a donor mobility scooter with additional fabrication added.'
          bottomBorder: '0'
          galleryId: ''
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Chassis and gallery 4'
        -
          enabled: '1'
          titlePrefix: ''
          title: ''
          titleTag: div
          content: "Plymouth/Chrysler Prowler Purple was chosen for the exterior paintwork colour, and the interior is Portland Grey vinyl and black acoustic carpet.\n\nPower comes from a 24v 3000rpm motor with forward and reverse, automatic motor braking on throttle release, and the model also features working headlights, horn, indicators, hazards, battery level indicator, door speakers with bluetooth connection and FM radio. Depending on the exact spec of the batteries, the range can be up to 35 miles!"
          bottomBorder: '0'
          galleryId: ''
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Paint, motor and gallery 5'
        -
          enabled: '1'
          titlePrefix: ''
          title: ''
          titleTag: div
          content: "Other details include:\n\n- Opening bonnet and boot lid.\n- 3D printed door mirrors and wipers.\n- Thermoformed windscreen, rear light covers and headlight bowls - exactly shaped to replicate the real thing.\n\nThe following YouTube video features many of the build photos and video clips showing the initial foam model being carved, through to the mould manufacture, chassis fabrication, body preparation and painting, and the final assembly, as well as it's first proper outing at the TVR Car Clubs 'Peaks to the Beach' event on the seafront at Rhyl back in July 2021."
          bottomBorder: '0'
          galleryId: ''
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Other details and YouTube'
