version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1691342274
layout:
  header: {  }
  navigation: {  }
  /hero/:
    -
      - herostaticcontent-4104
  heading: {  }
  row-1: {  }
  row-2: {  }
  row-3: {  }
  row-4: {  }
  row-5: {  }
  row-6: {  }
  row-7: {  }
  row-8: {  }
  row-9: {  }
  row-10: {  }
  footer: {  }
  inject: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  hero:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'bg-center bg-cover'
      background: 'gantry-media://hero/laptop-typing.jpg'
  heading:
    type: section
    inherit:
      outline: '21'
      include:
        - attributes
        - block
        - children
  row-1:
    type: section
    inherit:
      outline: '21'
      include:
        - attributes
        - block
        - children
  row-2:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-3:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-4:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-5:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-6:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-7:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-8:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-9:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-10:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  inject:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  herostaticcontent-4104:
    title: 'Hero Static Content'
    inherit:
      outline: '13'
      particle: herostaticcontent-4104
      include:
        - attributes
        - block
