version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1691342274
layout:
  header: {  }
  navigation: {  }
  /hero/:
    -
      - herostaticcontent-4104
  /row-1/:
    -
      - system-content-9488
  /row-2/: {  }
  /row-3/: {  }
  /row-4/: {  }
  /row-5/: {  }
  /row-6/: {  }
  /row-7/: {  }
  /row-8/: {  }
  /row-9/: {  }
  /row-10/: {  }
  footer: {  }
  inject: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  hero:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'bg-center bg-cover'
      background: 'gantry-media://hero/main-hero.jpg'
  row-1:
    type: section
    attributes:
      boxed: ''
      class: row-alt
      variations: ''
      background: ''
  row-2:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-3:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-4:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-5:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-6:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-7:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-8:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-9:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-10:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  inject:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  herostaticcontent-4104:
    title: 'Hero Static Content'
    attributes:
      class: ''
      variations: ''
      backgroundImage: ''
      backgroundSize: bg-cover
      backgroundPosition: bg-center
      contentStyleClass: content-flush
      titlePrefix: ''
      title: 'Steve Edwards'
      titleTag: h1
      titleLarge: '0'
      subtitle: 'Certificated Automotive Engineer (CAE), Associate Member of the Institute of the Motor Industry (AMIMI)'
      content: ''
      contentSize: full
      url: ''
      urlText: ''
      urlClass: ''
      searchInput: '0'
      disable: '0'
