version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1691342274
layout:
  header: {  }
  navigation: {  }
  hero: {  }
  /row-1/:
    -
      - contentblocks-1125
  /row-2/: {  }
  /row-3/: {  }
  /row-4/: {  }
  /row-5/: {  }
  /row-6/: {  }
  /row-7/: {  }
  /row-8/: {  }
  /row-9/: {  }
  /row-10/: {  }
  footer: {  }
  inject: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  hero:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  row-1:
    type: section
    attributes:
      boxed: ''
      class: row-alt
      variations: ''
      background: ''
  row-2:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-3:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-4:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-5:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-6:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-7:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-8:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-9:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-10:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  inject:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  contentblocks-1125:
    title: 'NASS Charter'
    attributes:
      class: ''
      items:
        -
          enabled: '1'
          titlePrefix: ''
          title: 'NASS Charter'
          titleTag: h2
          content: ''
          bottomBorder: '0'
          iconListItems: {  }
          buttonItems: {  }
          inject: ''
          cssid: ''
          class: small-schools-heading
          lightBorder: '0'
          notice: ''
          name: Heading
        -
          enabled: '1'
          titlePrefix: ''
          title: ''
          titleTag: div
          content: "**NASS promotes the work of smaller schools, those with 100 or fewer pupils. NASS believes that smallness of scale has worth.**\n\nNASS believes smaller schools offer ideal conditions for young children's learning. Personal attention leads to a sense of identity and a belief that effort is worthwhile. Loyal, committed teachers work as a team, with the children staying well on task. Small schools are caring places, close to home, family & community.\n\nTired old arguments that small schools cannot cope with the curriculum are now being thoroughly refuted in ways the public understands. In government inspections and national tests small schools are doing as well as and often better than the rest!\n\nNASS affirms that children in small schools are secure, work hard and co-operate effectively, are happy to accept responsibility, have self-esteem, behave very well. NASS believes that small schools are essential to the future well-being of society, ideally placed to serve as significant enterprises in their communities. Both the education of the children and the life of the community are enriched. NASS believes that small schools represent a valuable stake in community provision.\n\nPlease join us and help support our work."
          bottomBorder: '0'
          iconListItems: {  }
          buttonItems: {  }
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Charter text'
