version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1691342274
layout:
  header: {  }
  navigation: {  }
  hero: {  }
  /row-1/:
    -
      - system-content-4004
  /row-2/:
    -
      - contentblocks-6367
  row-3: {  }
  row-4: {  }
  row-5: {  }
  row-6: {  }
  row-7: {  }
  row-8: {  }
  row-9: {  }
  row-10: {  }
  footer: {  }
  inject: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  hero:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-1:
    type: section
    attributes:
      boxed: ''
      class: row-alt
      variations: ''
      background: ''
  row-2:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-3:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-4:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-5:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-6:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-7:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-8:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-9:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  row-10:
    type: section
    inherit:
      outline: '14'
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  inject:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  contentblocks-6367:
    title: 'Content Blocks'
    attributes:
      items:
        -
          enabled: '1'
          titlePrefix: ''
          title: 'A few photos of previous work'
          titleTag: h2
          content: ''
          bottomBorder: '0'
          galleryId: '11'
          iconListItems: {  }
          buttonItems: {  }
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Previous work'
