version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1691342274
layout:
  header: {  }
  navigation: {  }
  /hero/:
    -
      - herostaticcontent-4391
  heading: {  }
  /row-1/:
    -
      - contentblocks-5399
  row-2: {  }
  row-3: {  }
  row-4: {  }
  row-5: {  }
  row-6: {  }
  row-7: {  }
  row-8: {  }
  row-9: {  }
  row-10: {  }
  footer: {  }
  inject: {  }
  offcanvas: {  }
structure:
  header:
    inherit:
      outline: default
      include:
        - attributes
        - children
  navigation:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  hero:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: 'bg-center bg-cover'
      background: 'gantry-media://hero/young-girls-writing.jpg'
  heading:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-1:
    type: section
    attributes:
      boxed: ''
      class: ''
      variations: ''
      background: ''
  row-2:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-3:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-4:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-5:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-6:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-7:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-8:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-9:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  row-10:
    type: section
    inherit:
      outline: '12'
      include:
        - attributes
        - block
        - children
  footer:
    inherit:
      outline: default
      include:
        - attributes
        - children
  inject:
    type: section
    inherit:
      outline: default
      include:
        - attributes
        - children
  offcanvas:
    inherit:
      outline: default
      include:
        - attributes
        - children
content:
  herostaticcontent-4391:
    title: 'Hero Static Content'
    attributes:
      class: nass-hero-content
      variations: ''
      backgroundImage: ''
      backgroundSize: bg-cover
      backgroundPosition: bg-center
      contentStyleClass: content-flush
      titlePrefix: ''
      title: 'Research and policy influence'
      titleTag: h1
      titleLarge: '0'
      subtitle: 'NASS - the voice of small schools'
      content: "NASS is a registered charity supporting and promoting the work of small schools across the UK.\n\n<a href=\"/home/join-nass\" class=\"btn-primary btn-arrow\">Join NASS</a>"
      contentSize: full
      url: ''
      urlText: ''
      urlClass: ''
      searchInput: '0'
      disable: '0'
  contentblocks-5399:
    title: 'Research and policy influence content'
    attributes:
      items:
        -
          enabled: '1'
          titlePrefix: ''
          title: Research
          titleTag: h2
          content: 'NASS is the perfect place for individuals who are interested in small school research. Our community provides a space for like-minded individuals to come together, learn, and share their knowledge.'
          bottomBorder: '0'
          iconListItems: {  }
          buttonItems: {  }
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: Research
        -
          enabled: '1'
          titlePrefix: ''
          title: 'Research spotlights database'
          titleTag: h2
          content: "Focus on the use of research evidence in schools is on the increase. However, it is often difficult for busy professionals to find the time to locate and read relevant reports. So, we are putting together a library of research spotlights which offer summaries of key findings of research papers and suggestions for how these might impact on practice.\L\L\n\nWeâ€™re aiming to make research more accessible and to support professionals and governors in small schools by identifying how research findings may be useful to them."
          bottomBorder: '0'
          iconListItems: {  }
          buttonItems: {  }
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Research spotlights database'
        -
          enabled: '1'
          titlePrefix: ''
          title: 'Policy influence'
          titleTag: h2
          content: 'Content to follow'
          bottomBorder: '0'
          inject: ''
          cssid: ''
          class: ''
          lightBorder: '0'
          notice: ''
          name: 'Policy influence'
